check transfer: TableEngine Class Reference
TableEngine Class Reference abstract
#include <table_engine.h>
Public Member Functions
virtual int AddRowTable ()=0
virtual void ClearTable ()=0
virtual int CreateTable (const char *pColumnName[], unsigned nCount, unsigned isTStudio)=0
virtual void GetConsolePos (int &X, int &Y)=0
virtual void SaveTable ()=0
virtual void SetConsolePos (int X, int Y)=0
virtual int SetValueTable (unsigned nRow, unsigned nColumn, const char *fmt,...)=0
virtual int SetValueTable (unsigned nRow, unsigned nColumn, const char *pVal)=0
virtual int SetValueTable (unsigned nRow, unsigned nColumn, signed nVal, const char *format="%d")=0
virtual int SetValueTable (unsigned nRow, unsigned nColumn, unsigned nVal, const char *format="%u")=0
virtual int SetValueTable (unsigned nRow, unsigned nColumn, float dVal, const char *format="%f")=0
TableEngine ()
virtual void UpdateTable ()=0
virtual ~TableEngine ()
Detailed Description
Definition at line 4 of file table_engine.h.
Constructor & Destructor Documentation
TableEngine()
TableEngine::TableEngine () inline
Definition at line 7 of file table_engine.h.
 {}
~TableEngine()
virtual TableEngine::~TableEngine () inline virtual
Definition at line 8 of file table_engine.h.
References AddRowTable(), ClearTable(), CreateTable(), GetConsolePos(), SaveTable(), SetConsolePos(), SetValueTable(), and UpdateTable().
 {}
Member Function Documentation
AddRowTable()
virtual int TableEngine::AddRowTable () pure virtual
Implemented in TableEngineConsole.
Referenced by TF_CheckTransferOut::Run(), and ~TableEngine().
ClearTable()
virtual void TableEngine::ClearTable () pure virtual
Implemented in TableEngineConsole.
Referenced by ~TableEngine().
CreateTable()
virtual int TableEngine::CreateTable (const char * pColumnName[], unsigned nCount, unsigned isTStudio) pure virtual
Implemented in TableEngineConsole.
Referenced by main(), and ~TableEngine().
GetConsolePos()
virtual void TableEngine::GetConsolePos (int & X, int & Y) pure virtual
Implemented in TableEngineConsole.
Referenced by main(), and ~TableEngine().
SaveTable()
virtual void TableEngine::SaveTable () pure virtual
Implemented in TableEngineConsole.
Referenced by ~TableEngine().
SetConsolePos()
virtual void TableEngine::SetConsolePos (int X, int Y) pure virtual
Implemented in TableEngineConsole.
Referenced by main(), and ~TableEngine().
SetValueTable() [1/5]
virtual int TableEngine::SetValueTable (unsigned nRow, unsigned nColumn, const char * fmt, ...) pure virtual
Implemented in TableEngineConsole.
Referenced by TF_CheckTransferOut::StepTable(), and ~TableEngine().
SetValueTable() [2/5]
virtual int TableEngine::SetValueTable (unsigned nRow, unsigned nColumn, const char * pVal) pure virtual
Implemented in TableEngineConsole.
SetValueTable() [3/5]
virtual int TableEngine::SetValueTable (unsigned nRow, unsigned nColumn, signed nVal, const char * format = "%d") pure virtual
Implemented in TableEngineConsole.
SetValueTable() [4/5]
virtual int TableEngine::SetValueTable (unsigned nRow, unsigned nColumn, unsigned nVal, const char * format = "%u") pure virtual
Implemented in TableEngineConsole.
SetValueTable() [5/5]
virtual int TableEngine::SetValueTable (unsigned nRow, unsigned nColumn, float dVal, const char * format = "%f") pure virtual
Implemented in TableEngineConsole.
UpdateTable()
virtual void TableEngine::UpdateTable () pure virtual
Implemented in TableEngineConsole.
Referenced by ~TableEngine().
The documentation for this class was generated from the following file:
host_util/table_engine.h