check transfer: TF_TestThread Class Reference
TF_TestThread Class Reference abstract
Base class for application with thread.
#include <tf_testthread.h>
Public Member Functions
virtual void CleanupInThread ()=0
void * Execute ()
virtual void GetResult ()
virtual void GetResultInThread ()=0
int GetStrFromCommnadLine (int argc, char **argv, const char *name, char *defValue, char *dst, int dstLen)
Get string value from command line.
virtual int isComplete ()
virtual int Prepare (int cnt)
virtual void PrepareInThread ()=0
virtual void Run ()=0
virtual void Start ()
virtual void StepTable ()=0
virtual void Stop ()
TF_TestThread (TableEngine *pTable, int argc, char **argv)
virtual ~TF_TestThread ()
Public Member Functions inherited from TF_Test
virtual void StepMainThread ()
TF_Test (TableEngine *pTable)
Static Public Member Functions
static int GetFromCommnadLine (int argc, char **argv, const char *name, int defValue)
Get integer value from command line.
static void * ThreadFunc (void *lpvThreadParm)
Public Attributes
pthread_attr_t m_attrThread
int m_CycleCnt
pthread_t m_hThread
int m_isComplete
int m_isException
int m_isPrepareComplete
int m_isTerminate
pthread_mutex_t m_ResultCompleteMutex
pthread_mutex_t m_ResultStartMutex
pthread_mutex_t m_StartMutex
pthread_mutex_t m_ThreadExitMutex
Public Attributes inherited from TF_Test
TableEngine * m_pTemplateEngine
Detailed Description
Base class for application with thread.
Definition at line 22 of file tf_testthread.h.
Constructor & Destructor Documentation
TF_TestThread()
TF_TestThread::TF_TestThread (TableEngine * pTable, int argc, char ** argv)
Definition at line 21 of file tf_testthread.cpp.
References m_CycleCnt, m_isComplete, m_isException, m_isPrepareComplete, m_isTerminate, m_ResultCompleteMutex, m_ResultStartMutex, m_StartMutex, and m_ThreadExitMutex.
                                                                          : TF_Test( pTable )
 {
     // TODO Auto-generated constructor stub
     //fprintf(stderr, "TF_TestThread::%s(): ID - %ld\n", __FUNCTION__, pthread_self());
     m_isPrepareComplete=0;
     m_isComplete=0;
     m_isTerminate=0;
     m_CycleCnt=0;
     m_isException=0;
     pthread_mutex_init(&m_ResultStartMutex, 0);
     pthread_mutex_init(&m_ResultCompleteMutex, 0);
     pthread_mutex_init(&m_StartMutex, 0);
     pthread_mutex_init(&m_ThreadExitMutex, 0);
     // Lock mutex for Start and GetResult
     pthread_mutex_lock(&m_ResultStartMutex);
     pthread_mutex_lock(&m_ResultCompleteMutex);
     pthread_mutex_lock(&m_StartMutex);
     //pthread_mutex_lock(&m_ThreadExitMutex);
 }
~TF_TestThread()
TF_TestThread::~TF_TestThread () virtual
Definition at line 48 of file tf_testthread.cpp.
References m_ThreadExitMutex.
 {
     //fprintf(stderr, "TF_TestThread::%s(): ID - %ld\n", __FUNCTION__, pthread_self());
     pthread_mutex_lock(&m_ThreadExitMutex);
     //fprintf(stderr, "TF_TestThread::%s(): ID - %ld (COMPLETE)\n", __FUNCTION__, pthread_self());
 }
Member Function Documentation
CleanupInThread()
virtual void TF_TestThread::CleanupInThread () pure virtual
Implemented in TF_CheckTransferOut.
Referenced by Execute().
Execute()
void * TF_TestThread::Execute ()
Definition at line 103 of file tf_testthread.cpp.
References CleanupInThread(), GetResultInThread(), _except_info_t::info, m_isComplete, m_isException, m_isPrepareComplete, m_ResultCompleteMutex, m_ResultStartMutex, m_StartMutex, m_ThreadExitMutex, PrepareInThread(), and Run().
Referenced by ThreadFunc().
 {
     try
     {
         pthread_mutex_lock(&m_ThreadExitMutex);
         PrepareInThread();
         m_isPrepareComplete = 1;
         // Sleep here while TF_TestThread::Start() will be called in another thread
         pthread_mutex_lock(&m_StartMutex);
         //fprintf(stderr, "TF_TestThread::%s(): ID - %ld (START)\n", __FUNCTION__, pthread_self());
         // Working forever while m_isTerminate == 0
         Run();
         m_isComplete = 1;
         // Wait while TF_TestThread::GetResult() will be called
         pthread_mutex_lock( &m_ResultStartMutex );
         GetResultInThread();
         // Unlock mutex for complete GetResult() execution
         pthread_mutex_unlock(&m_ResultCompleteMutex);
         CleanupInThread();
         // Unlock mutex for complete TF_TestThread::~TF_TestThread() execution
         pthread_mutex_unlock(&m_ThreadExitMutex);
         //fprintf(stderr, "TF_TestThread::%s(): ID - %ld (COMPLETE)\n", __FUNCTION__, pthread_self());
     }
     catch( except_info_t err )
     {
         printf( "\n\n\n\n\n\n\n                \n Error in thread:\n%s\n                 \n", err.info.c_str());
         m_isComplete = 1;
         m_isException = 1;
         pthread_mutex_unlock(&m_ThreadExitMutex);
     }
     catch( ... )
     {
         printf( "\n\n\n                \n Unknow error in thread\n                 \n" );
         m_isComplete = 1;
         m_isException = 1;
         pthread_mutex_unlock(&m_ThreadExitMutex);
     }
     return 0;
 }
GetFromCommnadLine()
int TF_TestThread::GetFromCommnadLine (int argc, char ** argv, const char * name, int defValue) static
Get integer value from command line.
format command line: <name1> <value1> <name2> <value2>
Parameters
argc number of argument
argv pointers to arguments
name key of argument
defValue default value for arguments
Returns
value of argument or default value of argument
Definition at line 227 of file tf_testthread.cpp.
Referenced by main(), and TF_CheckTransferOut::TF_CheckTransferOut().
 {
     int ret=defValue;
     for( int ii=1; ii<argc-1; ii++ )
     {
         if( 0==strcmp( argv[ii], name) )
         {
             ret=atoi( argv[ii+1] );
         }
     }
     return ret;
 }
GetResult()
void TF_TestThread::GetResult () virtual
Reimplemented from TF_Test.
Definition at line 189 of file tf_testthread.cpp.
References m_ResultCompleteMutex, and m_ResultStartMutex.
Referenced by main().
 {
     //fprintf(stderr, "TF_TestThread::%s(): ID - %ld (START)\n", __FUNCTION__, pthread_self());
     // Unlock mutex for finish Execute()
     pthread_mutex_unlock(&m_ResultStartMutex);
     //fprintf(stderr, "TF_TestThread::%s(): ID - %ld (Unlock m_ResultStartMutex)\n", __FUNCTION__, pthread_self());
     // Waiting here while GetResultInThread() will be called and complete from Execute();
     pthread_mutex_lock(&m_ResultCompleteMutex);
     //fprintf(stderr, "TF_TestThread::%s(): ID - %ld (COMPLETE)\n", __FUNCTION__, pthread_self());
 }
GetResultInThread()
virtual void TF_TestThread::GetResultInThread () pure virtual
Implemented in TF_CheckTransferOut.
Referenced by Execute().
GetStrFromCommnadLine()
int TF_TestThread::GetStrFromCommnadLine (int argc, char ** argv, const char * name, char * defValue, char * dst, int dstLen)
Get string value from command line.
format command line: <name1> <text1> <name2> <text2>
Parameters
argc number of argument
argv pointers to arguments
name key of argument
defValue default value for arguments
dst pointer to destination string, NULL - do not copy
dstLen max number of chars in the dst
Returns
0 - name not found, 1 - found only name, 2 - found name and text
Definition at line 256 of file tf_testthread.cpp.
Referenced by TF_CheckTransferOut::TF_CheckTransferOut().
 {
         int ret=0;
         int index=0;
         for( int ii=1; ii<argc; ii++ )
     {
         if( 0==strcmp( argv[ii], name) )
         {
                 if( ii==(argc-1) )
                         ret=1;
                 else
                 {
                         ret=2; index=ii;
                 }
                 break;
         }
     }
         if( NULL!=dst )
         {
                 if( 2==ret )
                         strncpy( dst, argv[index+1], dstLen );
                 else
                         strncpy( dst, defValue, dstLen );
                 dst[dstLen-1]=0;
         }
         return ret;
 }
isComplete()
int TF_TestThread::isComplete () virtual
Reimplemented from TF_Test.
Definition at line 179 of file tf_testthread.cpp.
References m_isComplete.
Referenced by main().
 {
     //if(m_isComplete > 0)
         //fprintf(stderr, "TF_TestThread::%s(): ID - %ld\n", __FUNCTION__, pthread_self());
     return m_isComplete;
 }
Prepare()
int TF_TestThread::Prepare (int cnt) virtual
Implements TF_Test.
Definition at line 57 of file tf_testthread.cpp.
References except_info(), m_attrThread, m_hThread, m_isException, m_isPrepareComplete, and ThreadFunc().
Referenced by main().
 {
     if( 0==cnt )
     {
         //fprintf(stderr, "TF_TestThread::%s(): ID - %ld\n", __FUNCTION__, pthread_self());
         int res = pthread_attr_init(&m_attrThread);
         if(res != 0) {
             fprintf(stderr, "%s\n", "Stream not started");
             throw( "Stream not started" );
         }
         res = pthread_attr_setdetachstate(&m_attrThread, PTHREAD_CREATE_JOINABLE);
         if(res != 0) {
             fprintf(stderr, "%s\n", "Stream not started");
             throw( "Stream not started" );
         }
         res = pthread_create(&m_hThread, &m_attrThread, ThreadFunc, this);
         if(res != 0) {
             fprintf(stderr, "%s\n", "Stream not started");
             throw( "Stream not started" );
         }
     }
     int ret=m_isPrepareComplete;
     if( m_isException )
     {
         throw except_info( "%s - exception during execute", __FUNCTION__ );
     }
     return ret;
 }
PrepareInThread()
virtual void TF_TestThread::PrepareInThread () pure virtual
Implemented in TF_CheckTransferOut.
Referenced by Execute().
Run()
virtual void TF_TestThread::Run () pure virtual
Implemented in TF_CheckTransferOut.
Referenced by Execute().
Start()
void TF_TestThread::Start () virtual
Implements TF_Test.
Definition at line 162 of file tf_testthread.cpp.
References m_StartMutex.
Referenced by main().
 {
     // Unlock mutex for unblock TF_TestThread::Execute() function
     pthread_mutex_unlock(&m_StartMutex);
     //fprintf(stderr, "TF_TestThread::%s(): ID - %ld\n", __FUNCTION__, pthread_self());
 }
StepTable()
virtual void TF_TestThread::StepTable () pure virtual
Reimplemented from TF_Test.
Implemented in TF_CheckTransferOut.
Stop()
void TF_TestThread::Stop () virtual
Reimplemented from TF_Test.
Definition at line 171 of file tf_testthread.cpp.
References m_isTerminate.
Referenced by main().
 {
     m_isTerminate = 1;
     //fprintf(stderr, "TF_TestThread::%s(): ID - %ld\n", __FUNCTION__, pthread_self());
 }
ThreadFunc()
void * TF_TestThread::ThreadFunc (void * lpvThreadParm) static
Definition at line 92 of file tf_testthread.cpp.
References Execute().
Referenced by Prepare().
 {
     TF_TestThread *test=(TF_TestThread*)lpvThreadParm;
     if(!test)
         return 0;
     //fprintf(stderr, "TF_TestThread::%s(): ID - %ld\n", __FUNCTION__, pthread_self());
     return test->Execute();
 }
Member Data Documentation
m_attrThread
pthread_attr_t TF_TestThread::m_attrThread
Definition at line 57 of file tf_testthread.h.
Referenced by Prepare().
m_CycleCnt
int TF_TestThread::m_CycleCnt
Definition at line 48 of file tf_testthread.h.
Referenced by TF_TestThread().
m_hThread
pthread_t TF_TestThread::m_hThread
Definition at line 56 of file tf_testthread.h.
Referenced by Prepare().
m_isComplete
int TF_TestThread::m_isComplete
Definition at line 46 of file tf_testthread.h.
Referenced by Execute(), isComplete(), and TF_TestThread().
m_isException
int TF_TestThread::m_isException
Definition at line 49 of file tf_testthread.h.
Referenced by Execute(), Prepare(), and TF_TestThread().
m_isPrepareComplete
int TF_TestThread::m_isPrepareComplete
Definition at line 45 of file tf_testthread.h.
Referenced by Execute(), Prepare(), and TF_TestThread().
m_isTerminate
int TF_TestThread::m_isTerminate
Definition at line 47 of file tf_testthread.h.
Referenced by TF_CheckTransferOut::Run(), Stop(), and TF_TestThread().
m_ResultCompleteMutex
pthread_mutex_t TF_TestThread::m_ResultCompleteMutex
Definition at line 52 of file tf_testthread.h.
Referenced by Execute(), GetResult(), and TF_TestThread().
m_ResultStartMutex
pthread_mutex_t TF_TestThread::m_ResultStartMutex
Definition at line 51 of file tf_testthread.h.
Referenced by Execute(), GetResult(), and TF_TestThread().
m_StartMutex
pthread_mutex_t TF_TestThread::m_StartMutex
Definition at line 53 of file tf_testthread.h.
Referenced by Execute(), Start(), and TF_TestThread().
m_ThreadExitMutex
pthread_mutex_t TF_TestThread::m_ThreadExitMutex
Definition at line 54 of file tf_testthread.h.
Referenced by Execute(), TF_TestThread(), and ~TF_TestThread().
The documentation for this class was generated from the following files:
host_util/tf_testthread.h
host_util/tf_testthread.cpp