check transfer: TF_Test Class Reference
TF_Test Class Reference abstract
Base class for testing device.
#include <tf_test.h>
Public Member Functions
virtual void GetResult ()
virtual int isComplete ()
virtual int Prepare (int cnt)=0
virtual void Start ()=0
virtual void StepMainThread ()
virtual void StepTable ()
virtual void Stop ()
TF_Test (TableEngine *pTable)
Public Attributes
TableEngine * m_pTemplateEngine
Detailed Description
Base class for testing device.
Definition at line 16 of file tf_test.h.
Constructor & Destructor Documentation
TF_Test()
TF_Test::TF_Test (TableEngine * pTable) inline
Definition at line 23 of file tf_test.h.
References Prepare(), and Start().
     {
         m_pTemplateEngine = pTable;
     }
Member Function Documentation
GetResult()
virtual void TF_Test::GetResult () inline virtual
Reimplemented in TF_TestThread.
Definition at line 40 of file tf_test.h.
 {}
isComplete()
virtual int TF_Test::isComplete () inline virtual
Reimplemented in TF_TestThread.
Definition at line 34 of file tf_test.h.
 { return 0; }
Prepare()
virtual int TF_Test::Prepare (int cnt) pure virtual
Implemented in TF_TestThread.
Referenced by TF_Test().
Start()
virtual void TF_Test::Start () pure virtual
Implemented in TF_TestThread.
Referenced by TF_Test().
StepMainThread()
virtual void TF_Test::StepMainThread () inline virtual
Definition at line 38 of file tf_test.h.
Referenced by main().
 {}
StepTable()
virtual void TF_Test::StepTable () inline virtual
Reimplemented in TF_TestThread, and TF_CheckTransferOut.
Definition at line 36 of file tf_test.h.
 {}
Stop()
virtual void TF_Test::Stop () inline virtual
Reimplemented in TF_TestThread.
Definition at line 32 of file tf_test.h.
 {}
Member Data Documentation
m_pTemplateEngine
TableEngine* TF_Test::m_pTemplateEngine
Definition at line 21 of file tf_test.h.
Referenced by TF_CheckTransferOut::Run(), and TF_CheckTransferOut::StepTable().
The documentation for this class was generated from the following file:
host_util/tf_test.h