check transfer: host_util/exceptinfo.h File Reference
exceptinfo.h File Reference
#include <string>
Classes
struct _except_info_t
Typedefs
typedef struct _except_info_t except_info_t
Functions
except_info_t except_info (const char *fmt,...)
Typedef Documentation
except_info_t
typedef struct _except_info_t except_info_t
Function Documentation
except_info()
except_info_t except_info (const char * fmt, ...)
Definition at line 25 of file exceptinfo.cpp.
References _except_info_t::info.
Referenced by TF_TestThread::Prepare(), TF_CheckTransferOut::PrepareInThread(), TF_CheckTransferOut::Run(), and TF_CheckTransferOut::TF_CheckTransferOut().
 {
     except_info_t err;
     va_list argptr;
     va_start(argptr, fmt);
     char msg[256];
     vsprintf(msg, fmt, argptr);
     err.info = msg;
     return err;
 }