check transfer: host_util/parse_cmd.cpp File Reference
parse_cmd.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "parse_cmd.h"
Functions
int GetFromCommnadLine (int argc, char **argv, const char *name, int defValue)
Get integer value from command line.
int GetStrFromCommnadLine (int argc, char **argv, const char *name, char *defValue, char *dst, int dstLen)
Get string value from command line.
Function Documentation
GetFromCommnadLine()
int GetFromCommnadLine (int argc, char ** argv, const char * name, int defValue)
Get integer value from command line.
format command line: <name1> <value1> <name2> <value2>
Parameters
argc number of argument
argv pointers to arguments
name key of argument
defValue default value for arguments
Returns
value of argument or default value of argument
Definition at line 29 of file parse_cmd.cpp.
Referenced by main(), TF_CheckTransferIn::TF_CheckTransferIn(), and TF_CheckTransferOut::TF_CheckTransferOut().
 {
     int ret=defValue;
     for( int ii=1; ii<argc-1; ii++ )
     {
         if( 0==strcmp( argv[ii], name) )
         {
             ret=atoi( argv[ii+1] );
         }
     }
     return ret;
 }
GetStrFromCommnadLine()
int GetStrFromCommnadLine (int argc, char ** argv, const char * name, char * defValue, char * dst, int dstLen)
Get string value from command line.
format command line: <name1> <text1> <name2> <text2>
Parameters
argc number of argument
argv pointers to arguments
name key of argument
defValue default value for arguments
dst pointer to destination string, NULL - do not copy
dstLen max number of chars in the dst
Returns
0 - name not found, 1 - found only name, 2 - found name and text
Definition at line 58 of file parse_cmd.cpp.
Referenced by TF_Device::TF_Device().
 {
         int ret=0;
         int index=0;
         for( int ii=1; ii<argc; ii++ )
     {
         if( 0==strcmp( argv[ii], name) )
         {
                 if( ii==(argc-1) )
                         ret=1;
                 else
                 {
                         ret=2; index=ii;
                 }
                 break;
         }
     }
         if( NULL!=dst )
         {
                 if( 2==ret )
                         strncpy( dst, argv[index+1], dstLen );
                 else
                         strncpy( dst, defValue, dstLen );
                 dst[dstLen-1]=0;
         }
         return ret;
 }