check transfer: TableEngineConsole Class Reference
TableEngineConsole Class Reference
#include <table_engine_console.h>
Public Member Functions
int AddRowTable ()
void ClearTable ()
int CreateTable (const char *pColumnName[], unsigned nCount, unsigned isTStudio)
void GetConsolePos (int &X, int &Y)
void SaveTable ()
void SetConsolePos (int X, int Y)
int SetValueTable (unsigned nRow, unsigned nColumn, const char *fmt,...)
int SetValueTable (unsigned nRow, unsigned nColumn, const char *pVal)
int SetValueTable (unsigned nRow, unsigned nColumn, signed nVal, const char *format="%d")
int SetValueTable (unsigned nRow, unsigned nColumn, unsigned nVal, const char *format="%u")
int SetValueTable (unsigned nRow, unsigned nColumn, float dVal, const char *format="%f")
TableEngineConsole ()
void UpdateTable ()
~TableEngineConsole ()
Public Member Functions inherited from TableEngine
TableEngine ()
virtual ~TableEngine ()
Private Attributes
int flagTableCreate
Detailed Description
Definition at line 9 of file table_engine_console.h.
Constructor & Destructor Documentation
TableEngineConsole()
TableEngineConsole::TableEngineConsole ()
Definition at line 25 of file table_engine_console.cpp.
References CELL_HEIGHT, CELL_WIDTH, and flagTableCreate.
                                        : TableEngine()
 {
         flagTableCreate=0;
 #if defined(__linux__)
     rows.clear();
     m_C = m_R = 0;
     WC = CELL_WIDTH;
     HC = CELL_HEIGHT;
     WCL = 25;
 #else
 #endif
 }
~TableEngineConsole()
TableEngineConsole::~TableEngineConsole ()
Definition at line 40 of file table_engine_console.cpp.
 {
 #if defined(__linux__)
 #else
 #endif
 }
Member Function Documentation
AddRowTable()
int TableEngineConsole::AddRowTable () virtual
Implements TableEngine.
Definition at line 99 of file table_engine_console.cpp.
References row_t::c, _cell_t::col, flagTableCreate, row_t::num, _cell_t::row, _cell_t::x, and _cell_t::y.
 {
         if( 0==flagTableCreate )
                 return 0;
 #if defined(__linux__)
     row_t new_row;
     row_t& last_row = rows.at(rows.size()-1);
     new_row.num = last_row.num+1;
     for(int j=0; j<m_C; j++) {
         cell_t c;
         c.row = new_row.num;
         c.col = j;
         c.x = XC + c.col*WC;
         c.y = YC + c.row*HC;
         cell_draw(c.x, c.y, WC, HC);
         new_row.c.push_back(c);
     }
     m_R++;
     rows.push_back(new_row);
     cell_draw_fix();
 #else
 #endif
     return rows.size()-1;
 }
ClearTable()
void TableEngineConsole::ClearTable () virtual
Implements TableEngine.
Definition at line 195 of file table_engine_console.cpp.
 {
 #if defined(__linux__)
 #else
 #endif
 }
CreateTable()
int TableEngineConsole::CreateTable (const char * pColumnName[], unsigned nCount, unsigned isTStudio) virtual
Implements TableEngine.
Definition at line 49 of file table_engine_console.cpp.
References row_t::c, _cell_t::col, flagTableCreate, row_t::num, _cell_t::row, SetValueTable(), _cell_t::x, and _cell_t::y.
 {
 #if defined(__linux__)
     get_screen(&WS, &HS);
     get_pos(&XC, &YC);
     if(HS-YC < 20) {
         system("clear");
         YC = 1;
     }
     m_C = nCount;
     m_R = 1;
     for(int i=0; i<m_R; i++) {
         row_t row;
         for(unsigned j=0; j<nCount; j++) {
             cell_t c;
             c.row = i;
             c.col = j;
             c.x = XC + j*WC;
             c.y = YC + i*HC;
             cell_draw(c.x, c.y, WC, HC);
             row.c.push_back(c);
         }
         row.num = i;
         rows.push_back(row);
     }
     cell_draw_fix();
     for(unsigned i=0; i<nCount; i++) {
         SetValueTable(0, i, "%s", pColumnName[i]);
     }
     flagTableCreate=1;
     return 0;
 #else
 #endif
 }
GetConsolePos()
void TableEngineConsole::GetConsolePos (int & X, int & Y) virtual
Implements TableEngine.
Definition at line 222 of file table_engine_console.cpp.
 {
 #if defined(__linux__)
     get_pos(&X, &Y);
 #else
 #endif
 }
SaveTable()
void TableEngineConsole::SaveTable () virtual
Implements TableEngine.
Definition at line 204 of file table_engine_console.cpp.
 {
 #if defined(__linux__)
 #else
 #endif
 }
SetConsolePos()
void TableEngineConsole::SetConsolePos (int X, int Y) virtual
Implements TableEngine.
Definition at line 232 of file table_engine_console.cpp.
References gotoxy.
 {
 #if defined(__linux__)
     gotoxy(X, Y);
 #endif
 }
SetValueTable() [1/5]
int TableEngineConsole::SetValueTable (unsigned nRow, unsigned nColumn, const char * fmt, ...) virtual
Implements TableEngine.
Definition at line 135 of file table_engine_console.cpp.
References gotoxy, _cell_t::x, and _cell_t::y.
Referenced by CreateTable(), and SetValueTable().
 {
 #if defined(__linux__)
     cell_t& c = get_cell(nRow, nColumn);
     gotoxy(c.x+2, c.y+1);
     va_list argptr;
     va_start(argptr, fmt);
     char msg[32];
     vsprintf(msg, fmt, argptr);
     printf("%s\n", msg);
 #endif
     return 0;
 }
SetValueTable() [2/5]
int TableEngineConsole::SetValueTable (unsigned nRow, unsigned nColumn, const char * pVal) virtual
Implements TableEngine.
Definition at line 151 of file table_engine_console.cpp.
References SetValueTable().
 {
 #if defined(__linux__)
     SetValueTable(nRow, nColumn, "%s", pVal);
 #else
 #endif
     return 0;
 }
SetValueTable() [3/5]
int TableEngineConsole::SetValueTable (unsigned nRow, unsigned nColumn, signed nVal, const char * format = "%d") virtual
Implements TableEngine.
Definition at line 162 of file table_engine_console.cpp.
References SetValueTable().
 {
 #if defined(__linux__)
     SetValueTable(nRow, nColumn, format, nVal);
 #else
 #endif
     return 0;
 }
SetValueTable() [4/5]
int TableEngineConsole::SetValueTable (unsigned nRow, unsigned nColumn, unsigned nVal, const char * format = "%u") virtual
Implements TableEngine.
Definition at line 173 of file table_engine_console.cpp.
References SetValueTable().
 {
 #if defined(__linux__)
     SetValueTable(nRow, nColumn, format, nVal);
 #else
 #endif
     return 0;
 }
SetValueTable() [5/5]
int TableEngineConsole::SetValueTable (unsigned nRow, unsigned nColumn, float dVal, const char * format = "%f") virtual
Implements TableEngine.
Definition at line 184 of file table_engine_console.cpp.
References SetValueTable().
 {
 #if defined(__linux__)
     SetValueTable(nRow, nColumn, format, dVal);
 #else
 #endif
     return 0;
 }
UpdateTable()
void TableEngineConsole::UpdateTable () virtual
Implements TableEngine.
Definition at line 213 of file table_engine_console.cpp.
 {
 #if defined(__linux__)
 #else
 #endif
 }
Member Data Documentation
flagTableCreate
int TableEngineConsole::flagTableCreate private
Definition at line 30 of file table_engine_console.h.
Referenced by AddRowTable(), CreateTable(), and TableEngineConsole().
The documentation for this class was generated from the following files:
host_util/table_engine_console.h
host_util/table_engine_console.cpp