check transfer: host_util/ipc.h File Reference
ipc.h File Reference
Functions
void IPC_delay (int ms)
int IPC_getch (void)
int IPC_getche (void)
long IPC_getTickCount ()
int IPC_kbhit (void)
Function Documentation
IPC_delay()
void IPC_delay (int ms)
Definition at line 16 of file ipc.cpp.
Referenced by main().
 {
     struct timeval tv = {0, 0};
     tv.tv_usec = 1000*ms;
     select(0,NULL,NULL,NULL,&tv);
 }
IPC_getch()
int IPC_getch (void)
Definition at line 26 of file ipc.cpp.
Referenced by IPC_getche(), and main().
 {
     int ch;
     while(1)
     {
         size_t size = 0;
     if (ioctl(STDIN_FILENO, FIONREAD, &size) == -1)
             size = 0;
         if(size)
     {
         ch = getchar();
         //read(0, &ch, 1);
         //DEBUG_PRINT("%s(): ch = %d\n", __FUNCTION__, ch );
         break;
     }
     }
     return ch;
 }
IPC_getche()
int IPC_getche (void)
Definition at line 48 of file ipc.cpp.
References IPC_getch().
 {
     return IPC_getch();
 }
IPC_getTickCount()
long IPC_getTickCount ()
Definition at line 66 of file ipc.cpp.
Referenced by main().
 {
    return time(NULL) * 1000;
 }
IPC_kbhit()
int IPC_kbhit (void)
Definition at line 55 of file ipc.cpp.
Referenced by main().
 {
     size_t size = 0;
     if (ioctl(STDIN_FILENO, FIONREAD, &size) == -1)
         return 0;
     //DEBUG_PRINT("%s(): size = %d\n", __FUNCTION__, size );
     return size;
 }