check transfer: aligned_allocator< T > Struct Template Reference
aligned_allocator< T > Struct Template Reference
#include <xcl2.hpp>
Public Types
using value_type = T
Public Member Functions
T * allocate (std::size_t num)
void deallocate (T *p, std::size_t num)
Detailed Description
template<typename T>
struct aligned_allocator< T >
Definition at line 52 of file xcl2.hpp.
Member Typedef Documentation
value_type
template<typename T > using aligned_allocator< T >::value_type = T
Definition at line 54 of file xcl2.hpp.
Member Function Documentation
allocate()
template<typename T > T* aligned_allocator< T >::allocate (std::size_t num) inline
Definition at line 55 of file xcl2.hpp.
   {
     void* ptr = nullptr;
     if (posix_memalign(&ptr,4096,num*sizeof(T)))
       throw std::bad_alloc();
     return reinterpret_cast<T*>(ptr);
   }
deallocate()
template<typename T > void aligned_allocator< T >::deallocate (T * p, std::size_t num) inline
Definition at line 62 of file xcl2.hpp.
References xcl::find_binary_file(), xcl::get_devices(), xcl::get_xil_devices(), xcl::import_binary_file(), xcl::is_emulation(), and xcl::is_hw_emulation().
   {
     free(p);
   }
The documentation for this struct was generated from the following file:
host_util/xcl2.hpp